[project]
name = "project-speech-processing"
version = "0.1.0"
description = "Aqui vamos a explorar ferramentas de processamento de fala"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "speechrecognition>=3.14.3",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
